--------------------------------------------------------
--  파일이 생성됨 - 월요일-11월-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REPLY
--------------------------------------------------------

  CREATE TABLE "NUSANGUSER"."REPLY" 
   (	"REPLYNO" NUMBER, 
	"USERNO" NUMBER DEFAULT 1, 
	"POSTNO" NUMBER, 
	"TEXTBODY" CLOB, 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"STATE" NUMBER DEFAULT 1, 
	"CHILD_REPLYNO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" 
 LOB ("TEXTBODY") STORE AS BASICFILE (
  TABLESPACE "ADMIN" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into NUSANGUSER.REPLY
SET DEFINE OFF;
Insert into NUSANGUSER.REPLY (REPLYNO,USERNO,POSTNO,REGDATE,STATE,CHILD_REPLYNO) values (1,1,15,to_date('20/11/09','RR/MM/DD'),0,null);
--------------------------------------------------------
--  DDL for Index SYS_C0010203
--------------------------------------------------------

  CREATE UNIQUE INDEX "NUSANGUSER"."SYS_C0010203" ON "NUSANGUSER"."REPLY" ("REPLYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Trigger TRI_REPLY_REPLYNO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "NUSANGUSER"."TRI_REPLY_REPLYNO" BEFORE INSERT ON REPLY
FOR EACH ROW
BEGIN
	SELECT SEQ_REPLY_REPLYNO.nextval
	INTO :new.REPLYNO
	FROM dual;
END;


/
ALTER TRIGGER "NUSANGUSER"."TRI_REPLY_REPLYNO" ENABLE;
--------------------------------------------------------
--  Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "NUSANGUSER"."REPLY" ADD CONSTRAINT "SYS_C0010203" PRIMARY KEY ("REPLYNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN"  ENABLE;
  ALTER TABLE "NUSANGUSER"."REPLY" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "NUSANGUSER"."REPLY" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "NUSANGUSER"."REPLY" MODIFY ("TEXTBODY" NOT NULL ENABLE);
  ALTER TABLE "NUSANGUSER"."REPLY" MODIFY ("POSTNO" NOT NULL ENABLE);
  ALTER TABLE "NUSANGUSER"."REPLY" MODIFY ("USERNO" NOT NULL ENABLE);
  ALTER TABLE "NUSANGUSER"."REPLY" MODIFY ("REPLYNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "NUSANGUSER"."REPLY" ADD CONSTRAINT "SYS_C0010231" FOREIGN KEY ("POSTNO")
	  REFERENCES "NUSANGUSER"."SELLPOST" ("POSTNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "NUSANGUSER"."REPLY" ADD CONSTRAINT "SYS_C0010235" FOREIGN KEY ("USERNO")
	  REFERENCES "NUSANGUSER"."NUSER" ("USERNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "NUSANGUSER"."REPLY" ADD CONSTRAINT "SYS_C0012153" FOREIGN KEY ("CHILD_REPLYNO")
	  REFERENCES "NUSANGUSER"."REPLY" ("REPLYNO") ON DELETE CASCADE ENABLE;
