--------------------------------------------------------
--  파일이 생성됨 - 월요일-11월-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SELLPOST
--------------------------------------------------------
drop table "NUSANGUSER"."SELLPOST" CASCADE CONSTRAINTS;
  CREATE TABLE "NUSANGUSER"."SELLPOST" 
   (	"POSTNO" NUMBER, 
	"TITLE" VARCHAR2(100 BYTE), 
	"BODYTEXT" VARCHAR2(4000 BYTE), 
	"PRICE" NUMBER, 
	"PRODUCTNAME" VARCHAR2(500 BYTE), 
	"USERNO" NUMBER DEFAULT 1, 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"CATEGORY" VARCHAR2(100 BYTE), 
	"SELLSTATE" NUMBER DEFAULT 0, 
	"VIEWCNT" NUMBER DEFAULT 0, 
	"VISIBLE" NUMBER DEFAULT 1, 
	"LOCATIONNO" NUMBER, 
	"POST_PICNO" NUMBER, 
	"HEARTCNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
REM INSERTING into NUSANGUSER.SELLPOST
SET DEFINE OFF;
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (3,null,'프레시오 시계 팝니다','프레시오 시계 사세요.
거저입니다.',30000,'프레시오 시계',2,to_date('20/11/09','RR/MM/DD'),'남성패션/잡화',0,1,1,9,5,1);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (4,null,'패트리모니 팜니다','상태B+ 상태대비 매우 저렴
정품100% 풀박스
가품일시 바로앞에 법원ㄱㄱ',30000000,'바쉐론콘스탄틴 로즈골드 ',1,to_date('20/11/09','RR/MM/DD'),'남성패션/잡화',2,4,1,11,6,0);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (5,null,'카시오 전자시계','가죽밴드',15000,'시계',6,to_date('20/11/09','RR/MM/DD'),'남성패션/잡화',0,4,1,12,7,4);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (11,null,'홈메이드 쿠키 판매합니다','버터/초코/아몬드/녹차맛 있습니다 개당1000원입니다.<br>품목,수량 적어주세요!<br>직거래는 남성역 주변에서만 합니다. ',1000,'수제쿠키',1,to_date('20/11/09','RR/MM/DD'),'생활/가공식품',0,2,1,19,13,0);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (10,null,'퓨마 롱패딩(xxl) 팔아요 거의 새거에 가까운 퓨마 롱패딩','푸마 롱패딩 팔아요 거의 새거에 가까운<br><br>불빵 이런거 찢어진거 없습니다<br>환불불가 사이즈 110<br>봉천동 거래가능합니다   ',80000,'퓨마 롱패딩',7,to_date('20/11/09','RR/MM/DD'),'남성패션/잡화',0,3,1,18,12,0);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (8,null,'카시오 가죽밴드 시계팔아요','5만원에샀어요 싸게팔아요 ',18000,'시계',6,to_date('20/11/09','RR/MM/DD'),'남성패션/잡화',0,4,1,15,10,1);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (9,null,'여성 코트 팜니다','보세옷입니다.  착샷입니다  ',30000,'보세 울코트',1,to_date('20/11/09','RR/MM/DD'),'여성의류',0,3,1,17,11,1);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (12,null,'더클래스 가죽클리너 ㅍㅍㅍㅍ','2만원에샀어요 얼마안썼어용',8000,'가죽클리너',6,to_date('20/11/09','RR/MM/DD'),'생활/가공식품',0,3,1,20,14,0);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (13,null,'지샥 DW-9052 급처!!!','지샥 DW-9052 급처 합니다!!<br>50만원에 샀는데 5만원 급처!!<br>네고 없습니다      ',50000,'지샥 DW-9052',2,to_date('20/11/09','RR/MM/DD'),'남성패션/잡화',0,3,1,21,15,0);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (14,null,'대형 돗자리 팔아요','7천원에 샀는데 깨끗하게 잘썼어요 ',3000,'돗자리',6,to_date('20/11/09','RR/MM/DD'),'생활/가공식품',0,2,1,22,16,0);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (15,null,'다이어트곡물쉐이크 팔아요','다이어트하려고 구매한 곡물쉐이크 판매합니다<br>1box 열개들어있구요~<br>수량은 넉넉하니 문의주세용^^<br>낱개로도 구매가능합니다<br>',7000,'다이어트곡물쉐이크',7,to_date('20/11/09','RR/MM/DD'),'생활/가공식품',0,2,1,23,17,3);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (16,null,'뉴발 롱패딩 블랙 M 팝니다','사서 한 번 입고 자금난으로 팝니다.
신품이나 다름 없으니 네고 사절입니다.',110000,'뉴발란스 롱패딩',2,to_date('20/11/09','RR/MM/DD'),'남성패션/잡화',0,3,1,24,18,1);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (17,null,'카시오 시계 팝니다','카시오 시계 팝니다.<br>가격제시 부탁해요 ',120000,'카시오(가죽)',2,to_date('20/11/09','RR/MM/DD'),'남성패션/잡화',0,1,1,25,19,0);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (1,null,'카시오 시계 팜니다','모델명 까먹었습니다.....   ',25000,'카시오시계(우레탄)',1,to_date('20/11/09','RR/MM/DD'),'남성패션/잡화',2,2,1,3,1,2);
Insert into NUSANGUSER.SELLPOST (POSTNO,PICTURE,TITLE,BODYTEXT,PRICE,PRODUCTNAME,USERNO,REGDATE,CATEGORY,SELLSTATE,VIEWCNT,VISIBLE,LOCATIONNO,POST_PICNO,HEARTCNT) values (2,null,'지샥','산지6개월 됐는데 한번도 안썼습ㅂ니당  내고 가능  ',150000,'우레탄지샥시계',5,to_date('20/11/09','RR/MM/DD'),'남성패션/잡화',0,4,1,5,2,2);
--------------------------------------------------------
--  DDL for Index SYS_C0010215
--------------------------------------------------------

  CREATE UNIQUE INDEX "NUSANGUSER"."SYS_C0010215" ON "NUSANGUSER"."SELLPOST" ("POSTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN" ;
--------------------------------------------------------
--  DDL for Trigger TRI_SELLPOST_POSTNO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "NUSANGUSER"."TRI_SELLPOST_POSTNO" BEFORE INSERT ON SELLPOST
FOR EACH ROW
BEGIN
	SELECT SEQ_SELLPOST_POSTNO.nextval
	INTO :new.POSTNO
	FROM dual;
END;


/
ALTER TRIGGER "NUSANGUSER"."TRI_SELLPOST_POSTNO" ENABLE;
--------------------------------------------------------
--  Constraints for Table SELLPOST
--------------------------------------------------------

  ALTER TABLE "NUSANGUSER"."SELLPOST" ADD CONSTRAINT "SYS_C0010215" PRIMARY KEY ("POSTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN"  ENABLE;
  ALTER TABLE "NUSANGUSER"."SELLPOST" MODIFY ("POST_PICNO" NOT NULL ENABLE);
  ALTER TABLE "NUSANGUSER"."SELLPOST" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "NUSANGUSER"."SELLPOST" MODIFY ("USERNO" NOT NULL ENABLE);
  ALTER TABLE "NUSANGUSER"."SELLPOST" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "NUSANGUSER"."SELLPOST" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "NUSANGUSER"."SELLPOST" MODIFY ("POSTNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SELLPOST
--------------------------------------------------------

  ALTER TABLE "NUSANGUSER"."SELLPOST" ADD CONSTRAINT "SYS_C0010236" FOREIGN KEY ("USERNO")
	  REFERENCES "NUSANGUSER"."NUSER" ("USERNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "NUSANGUSER"."SELLPOST" ADD FOREIGN KEY ("LOCATIONNO")
	  REFERENCES "NUSANGUSER"."LOCATION" ("LOCATIONNO") ENABLE;
  ALTER TABLE "NUSANGUSER"."SELLPOST" ADD FOREIGN KEY ("POST_PICNO")
	  REFERENCES "NUSANGUSER"."POST_PICTURE" ("POST_PICNO") ON DELETE CASCADE ENABLE;
