


CREATE SEQUENCE SEQ_NUSER_USERNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PAYMENT_MARKET_PH_MARKETNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PAYMENT_USER_PH_USERNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_REPLY_REPLYNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SELLPOST_POSTNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_WATCHLIST_WATCHLISTNO INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE PAYMENT_MARKET
(
	PH_MARKETNO number NOT NULL,
	PAYMENTTYPE varchar2(10) NOT NULL,
	STATE number NOT NULL,
	NAME nchar(10) NOT NULL,
	USERNO number DEFAULT 1  NOT NULL,
	REGDATE date DEFAULT SYSDATE,
	IMPORT_UUID nchar(20) NOT NULL,
	PRIMARY KEY (PH_MARKETNO)
);


CREATE TABLE PAYMENT_USER
(
	PH_USERNO number NOT NULL,
	PRODUCTNAME nchar(20) NOT NULL,
	PRICE long NOT NULL,
	BUSINESS_PARTNER number NOT NULL,
	USERNO number DEFAULT 1  NOT NULL,
	STATE nchar(10) NOT NULL,
	REGDATE date NOT NULL,
	PRIMARY KEY (PH_USERNO)
);


CREATE TABLE REPLY
(
	REPLYNO number NOT NULL,
	USERNO number DEFAULT 1  NOT NULL,
	POSTNO number NOT NULL,
	TEXTBODY char(50) NOT NULL,
	REGDATE date DEFAULT SYSDATE NOT NULL,
	STATE number DEFAULT 1 NOT NULL,
	PRIMARY KEY (REPLYNO)
);


CREATE TABLE SELLPOST
(
	POSTNO number NOT NULL,
	PICTURE clob NOT NULL,
	TITLE nchar(20) NOT NULL,
	BODYTEXT clob NOT NULL,
	LATITUDE float,
	LONGTITUDE float,
	PRICE long NOT NULL,
	PRODUCTNAME varchar2(20) NOT NULL,
	USERNO number DEFAULT 1  NOT NULL,
	REGDATE date DEFAULT SYSDATE NOT NULL,
	CATEGORY nchar(20) NOT NULL,
	STATE nchar(10) NOT NULL,
	ADDRESS nchar(30) NOT NULL,
	PRIMARY KEY (POSTNO)
);


CREATE TABLE WATCHLIST
(
	USERNO number DEFAULT 1  NOT NULL,
	POSTNO number NOT NULL,
	WATCHLISTNO number NOT NULL,
	PRIMARY KEY (WATCHLISTNO)
);


CREATE TABLE NUSANGUSER.NUSER
(
	USERNO number DEFAULT 1  NOT NULL,
	USERID varchar2(50 char) NOT NULL UNIQUE,
	USERNAME varchar2(50 char) NOT NULL,
	PASSWORD varchar2(50 char) NOT NULL,
	ROLE varchar2(20 char) DEFAULT '''ROLE_USER'' ' NOT NULL,
	LOGINTYPE varchar2(10) NOT NULL,
	EMAIL varchar2(50) NOT NULL,
	LOCATION varchar2(30) NOT NULL,
	REGDATE date DEFAULT SYSDATE NOT NULL,
	CONSTRAINT SYS_C009884 PRIMARY KEY (USERNO)
);



/* Create Foreign Keys */

ALTER TABLE REPLY
	ADD FOREIGN KEY (POSTNO)
	REFERENCES SELLPOST (POSTNO)
;


ALTER TABLE WATCHLIST
	ADD FOREIGN KEY (POSTNO)
	REFERENCES SELLPOST (POSTNO)
;


ALTER TABLE PAYMENT_MARKET
	ADD FOREIGN KEY (USERNO)
	REFERENCES NUSANGUSER.NUSER (USERNO)
;


ALTER TABLE PAYMENT_USER
	ADD FOREIGN KEY (USERNO)
	REFERENCES NUSANGUSER.NUSER (USERNO)
;


ALTER TABLE REPLY
	ADD FOREIGN KEY (USERNO)
	REFERENCES NUSANGUSER.NUSER (USERNO)
;


ALTER TABLE SELLPOST
	ADD FOREIGN KEY (USERNO)
	REFERENCES NUSANGUSER.NUSER (USERNO)
;


ALTER TABLE WATCHLIST
	ADD FOREIGN KEY (USERNO)
	REFERENCES NUSANGUSER.NUSER (USERNO)
;



/* Create Triggers */

CREATE OR REPLACE TRIGGER TRI_NUSER_USERNO BEFORE INSERT ON NUSER
FOR EACH ROW
BEGIN
	SELECT SEQ_NUSER_USERNO.nextval
	INTO :new.USERNO
	FROM dual;
END;

/





CREATE OR REPLACE TRIGGER TRI_PAYMENT_MARKET_PH_MARKETNO BEFORE INSERT ON PAYMENT_MARKET
FOR EACH ROW
BEGIN
	SELECT SEQ_PAYMENT_MARKET_PH_MARKETNO.nextval
	INTO :new.PH_MARKETNO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_PAYMENT_USER_PH_USERNO BEFORE INSERT ON PAYMENT_USER
FOR EACH ROW
BEGIN
	SELECT SEQ_PAYMENT_USER_PH_USERNO.nextval
	INTO :new.PH_USERNO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_REPLY_REPLYNO BEFORE INSERT ON REPLY
FOR EACH ROW
BEGIN
	SELECT SEQ_REPLY_REPLYNO.nextval
	INTO :new.REPLYNO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_SELLPOST_POSTNO BEFORE INSERT ON SELLPOST
FOR EACH ROW
BEGIN
	SELECT SEQ_SELLPOST_POSTNO.nextval
	INTO :new.POSTNO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_WATCHLIST_WATCHLISTNO BEFORE INSERT ON WATCHLIST
FOR EACH ROW
BEGIN
	SELECT SEQ_WATCHLIST_WATCHLISTNO.nextval
	INTO :new.WATCHLISTNO
	FROM dual;
END;

/


commit


